apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: consumer
  namespace: projeto-orquestracao
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
